export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ALL_MEMO = "GET_ALL_MEMO";
export const SET_IDMEMO_CLICKED = "SET_IDMEMO_CLICKED";
export const SET_IDCATEGORY_CLICKED = "SET_IDCATEGORY_CLICKED";
export const UPDATE_MEMO_ITEM = "UPDATE_MEMO_ITEM";
export const ADD_NEW_MEMO = "ADD_NEW_MEMO";
export const DELETE_ONE_MEMO = "DELETE_ONE_MEMO";
