export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ALL_MEMO = "GET_ALL_MEMO";
export const SET_IDMEMO_CLICKED = "SET_IDMEMO_CLICKED";
export const SET_IDCATEGORY_CLICKED = "SET_IDCATEGORY_CLICKED";
